[project]
name = "hello-world"
version = "0"
requires-python = "==3.14.*"
dependencies = [
    "fastapi",
    "granian",
    "stamina"
]

[dependency-groups]
dev = ["fastapi[standard]", "pytest"]

[build-system]
requires = ["uv_build>=0.9.17,<0.10.0"]
build-backend = "uv_build"